/// Flutter icons Dollar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dollar
///      fonts:
///       - asset: fonts/Dollar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Dollar {
  Dollar._();

  static const _kFontFam = 'Dollar';
  static const _kFontPkg = null;

  static const IconData faq = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData premium = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
